### ISSUE TITLE
CommandPacket Checksum

### ISSUE THREAD

**Issue by FastFrench** [FICTURE7/CoCSharp#39]
Hello,

first, thanks a lot for this great project. Really very useful. We were working on a MiM bot, and this decided us to try to do it completely without the CoC client. 
It works nicely with simple behaviours. But I guess all about commands couldn't work yet, because of the missing CheckSum computation needed in the CommandPacket (alias ClientEndTurn). 

Could you confirm that commands are not usable for now (except for reading, that is in a proxy mode with the CoC official client, or with private servers that do not care about this checksum)?
Do you think you may implement it? As it seems to be dépendent on many different data from the game, it may be quite challenging to add that. 
Or is there any trick to do without it?

Cheers, 

FF

**Comment by FICTURE7** [comment]
Yes, CommandPacket is not really usable, but you can read it and if I start to implement the way that the checksums are calculated, it would be game breaking. Because people could just make bots that plays Clash of Clans 24/7 which would be insane and I feel that CoCSharp.Client is powerful enough as it can stay online forever, giving players using it invisible shields.

But, time will tell if I will implement the checksum or someone else will. :]
and I don't know if there is a trick to it, but I think that the checksum is the same every 1st tick.

**Comment by FastFrench** [comment]
Thanks for your answer. 
I'm not convinced that it would really change the number of bots (there're already many bots, they simply rely on the CoC client). 
But I understand your point. 

I think that you're right: as long as nothing has changed between 2 successive logins, the checksum may remain the same at start. Then the tickCounter make it change, as do commands (current and any previous command since login). I'm reluctant at reversing CoC Library, but it's probably the only way to do it.

**Comment by FICTURE7** [comment]
Good luck with your project! :]
