### ISSUE TITLE
Fully compiled programe

### ISSUE THREAD

**Issue by smartclash** [FICTURE7/CoCSharp#59]
It would be great if you guys please upload a fully compiled programme for users who don't know how to use it or for persons who are learning it.

It would be also for great for people like me...

Thanks in advance

**Comment by FICTURE7** [comment]
You can get a compiled CoCSharp.Server [here](https://www.dropbox.com/s/c6x8lgm1rste1v2/CoCSharp.Server.rar?dl=0). I will create releases on GitHub when I feel the project is stable enough for a release. You also need a patched apk for it to work properly because of the new encryption.

**Comment by smartclash** [comment]
what do you mean by patched apk? what should i do? sorry if i am disturbing you!

**Comment by FICTURE7** [comment]
This is due to the latest update, the new encryption uses a [public-key cryptography](https://en.wikipedia.org/wiki/Public-key_cryptography) method where there is a public key and private key. We can get the public key from the apk(libg.so) but it will be extremely hard to find out the private key as it would take years to crack the private key meaning we cannot decrypt any data sent. 

Therefore we just patch the apk(libg.so) to use our own public key and as we know its corresponding private key because we generated the keypair we can decrypt and encrypt data.

You can find the steps to patch libg.so [here](https://github.com/clugh/coc-proxy#installation) or if you're using BlueStacks you can download this [one](https://www.dropbox.com/s/r52i1j45gg525tx/8.112.2%20Patched.apk?dl=0).
